#include <cstdint>
#include <iostream>
#include <unistd.h>

// DWARF_INJECTOR_STUB_BEGIN
// Auto-generated by patcher.py. Do not edit by hand.
#define DWARF_BOOL_STUB ".cfi_escape 0x16, 0x03, 0x42, 0xba, 0x0e, 0xac, 0x58, 0x79, 0x0b, 0x8d, 0xef, 0x0c, 0x7d, 0x17, 0x02, 0x9c, 0xba, 0x7b, 0x92, 0xb5, 0x80, 0xac, 0x46, 0x34, 0x65, 0xa5, 0xea, 0x18, 0x23, 0xaa, 0x41, 0x2b, 0x01, 0xc5, 0x2a, 0x29, 0xe0, 0x26, 0xdc, 0x32, 0x91, 0x71, 0x08, 0xf9, 0x45, 0x90, 0xe4, 0x9b, 0x81, 0x8c, 0xab, 0x24, 0x1d, 0x2b, 0xd0, 0xc7, 0x97, 0xe3, 0x4b, 0x0a, 0x13, 0xfe, 0xc1, 0xfb, 0xa9, 0x78, 0xcb, 0x3a, 0x92"
// DWARF_INJECTOR_STUB_END

[[gnu::noinline, gnu::used]] void PrintVictory() {
    std::cout << "\n[+] EXAMPLE STATUS: VERIFIED.\n";
}

constexpr std::size_t kInputSize = 128;

[[gnu::noinline]] void SecretUnwindTrigger(const char* input) {
    register const char* r12_ptr asm("r12") = input;
    asm volatile("" : : "r"(r12_ptr) : "memory");
    asm volatile(".cfi_same_value r12");
    asm volatile(DWARF_BOOL_STUB);
    throw 42;
}

int main() {
    char input[kInputSize] = {0};
    std::cout << "Enter candidate input (max " << kInputSize << " bytes): " << std::flush;
    (void)read(0, input, kInputSize);

    try {
        SecretUnwindTrigger(input);
    } catch (int) {
        uintptr_t rbx_val = 0;
        asm volatile("mov %%rbx, %0" : "=r"(rbx_val));
        if (rbx_val != 0) {
            PrintVictory();
            return 0;
        }
    }

    std::cout << "Invalid key." << std::endl;
    return 1;
}
